# Description.
model_template_id: Custom_Rotated_Detection_via_Instance_Segmentation_MaskRCNN_ResNet50
name: MaskRCNN-ResNet50
task_type: ROTATED_DETECTION
task_family: VISION
instantiation: "CLASS"
summary: Rotated object detection models detect objects as rotated bounding boxes. This model is based on MaskRCNN-ResNet50 which gives accurate predictions but slower during training and inference.
application: ~

# Algo backend.
framework: OTEDetection v2.9.1

# Task implementations.
entrypoints:
  base: detection_tasks.apis.detection.OTEDetectionTrainingTask
  openvino: detection_tasks.apis.detection.OpenVINODetectionTask
  nncf: detection_tasks.apis.detection.OTEDetectionNNCFTask

# Capabilities.
capabilities:
  - compute_representations

# Hyperparameters.
hyper_parameters:
  base_path: ../../../../mmdetection/detection_tasks/apis/detection/configuration.yaml
  parameter_overrides:
    learning_parameters:
      batch_size:
        default_value: 4
      learning_rate:
        default_value: 0.01
      learning_rate_warmup_iters:
        default_value: 200
      num_iters:
        default_value: 300
    nncf_optimization:
      enable_quantization:
        default_value: true
      enable_pruning:
        default_value: false
      maximal_accuracy_degradation:
        default_value: 1.0

# Training resources.
max_nodes: 1
training_targets:
  - GPU
  - CPU

# TODO[EUGENE]: WIP
# Stats.
gigaflops: 533.8
size: 177.9
