# Description.
model_template_id: Custom_Counting_Instance_Segmentation_MaskRCNN_ResNet50
name: MaskRCNN-EfficientNetB2B
task_type: INSTANCE_SEGMENTATION
task_family: VISION
instantiation: "CLASS"
summary: Class-Incremental Instance Segmentation for MaskRCNN-EfficientNetB2B
application: ~

# Algo backend.
framework: OTEDetection v2.9.1

# Task implementations.
entrypoints:
  base: mpa_tasks.apis.detection.DetectionTrainTask
  openvino: detection_tasks.apis.detection.OpenVINODetectionTask
  nncf: mpa_tasks.apis.detection.DetectionNNCFTask
base_model_path: ../../../../mmdetection/configs/custom-counting-instance-seg/efficientnetb2b_maskrcnn/template_experimental.yaml

# Capabilities.
capabilities: []

# Hyperparameters.
hyper_parameters:
  base_path: ../configuration.yaml
  parameter_overrides:
    learning_parameters:
      batch_size:
        default_value: 4
        auto_hpo_state: POSSIBLE
      learning_rate:
        default_value: 0.015
        auto_hpo_state: POSSIBLE
      learning_rate_warmup_iters:
        default_value: 200
      num_iters:
        default_value: 300
    algo_backend:
      train_type:
        default_value: Incremental

# Training resources.
max_nodes: 1
training_targets:
  - GPU
  - CPU

# Stats.
gigaflops: 68.48
size: 13.27
