# Description.
model_template_id: ClassIncremental_Instance_Segmentation_MaskRCNN_EfficientNetB2B
name: MaskRCNN-EfficientNetB2B-ClsIncr
task_type: INSTANCE_SEGMENTATION
task_family: VISION
instantiation: "CLASS"
summary: Class-Incremental Instance Segmentation for MaskRCNN-EfficientNetB2B
application: ~

# Algo backend.
framework: MPA v1.1.0

# Task implementations.
entrypoints:
  base: mpa_tasks.apis.detection.DetectionTrainTask
  openvino: detection_tasks.apis.detection.OpenVINODetectionTask

# Capabilities.
capabilities: []

# Hyperparameters.
hyper_parameters:
  base_path: ../configuration.yaml
  parameter_overrides:
    learning_parameters:
      batch_size:
        default_value: 4
      learning_rate:
        default_value: 0.015
      learning_rate_warmup_iters:
        default_value: 200
      num_iters:
        default_value: 300
    algo_backend:
      train_type:
        default_value: Incremental

# Training resources.
max_nodes: 1
training_targets:
  - GPU
  - CPU

# Stats.
gigaflops: 68.48
size: 13.27
