# Description.
model_template_id: ote_anomaly_detection_padim
name: PADIM
task_type: ANOMALY_DETECTION
task_family: VISION
instantiation: "CLASS"
summary: This model is faster and in many cases more accurate, but it requires a fixed position of the objects within the image.
application: ~

# Algo backend.
framework: OTEAnomalyClassification v0.1.0 # TODO: update after the name has been changed on the platform side

# Task implementations.
entrypoints:
  base: ote_anomalib.AnomalyTrainingTask
  openvino: ote_anomalib.OpenVINOAnomalyTask
  nncf: ote_anomalib.AnomalyNNCFTask

# Hyper Parameters
hyper_parameters:
  base_path: ./configuration.yaml

# Training resources.
max_nodes: 1
training_targets:
  - GPU
  - CPU

# Computational Complexity
gigaflops: 3.9
size: 168.4
