metric: accuracy_top-1
search_algorithm: asha
hp_space:
  learning_parameters.learning_rate:
    param_type: qloguniform
    range:
      - 0.0014
      - 0.035
      - 0.0001
  learning_parameters.batch_size:
    param_type: qloguniform
    range:
      - 40
      - 96
      - 2
