# Description.
model_template_id: ClassIncremental_Object_Detection_Gen3_SSD
name: SSD-ClsIncr
task_type: DETECTION
task_family: VISION
instantiation: "CLASS"
summary: Class-Incremental Object Detection for SSD
application: ~

# Algo backend.
framework: OTEDetection v2.9.1

# Task implementations.
entrypoints:
  base: mpa_tasks.apis.detection.DetectionTrainTask
  openvino: detection_tasks.apis.detection.OpenVINODetectionTask

# Capabilities.
capabilities: []

# Hyperparameters.
hyper_parameters:
  base_path: ../configuration.yaml
  parameter_overrides:
    learning_parameters:
      batch_size:
        default_value: 4
      learning_rate:
        default_value: 0.005
      learning_rate_warmup_iters:
        default_value: 200
      num_iters:
        default_value: 300
    algo_backend:
      train_type:
        default_value: Incremental

# Training resources.
max_nodes: 1
training_targets:
  - GPU
  - CPU

# Stats.
gigaflops: 20.6
size: 9.1
# # Inference options. Defined by OpenVINO capabilities, not Algo Backend or Platform.
# inference_targets:
#   - CPU
#   - GPU
#   - VPU
