# Description.
model_template_id: Custom_Semantic_Segmentation_Lite-HRNet-18_OCR
name: Lite-HRNet-18 OCR
task_type: SEGMENTATION
task_family: VISION
instantiation: "CLASS"
summary: Middle-sized architecture which based on the Lite-HRNet backbone with OCR head for the balance between the fast inference and long training.
application: ~

# Algo backend.
framework: OTESegmentation v0.14.0

# Task implementations.
entrypoints:
  base: segmentation_tasks.apis.segmentation.OTESegmentationTrainingTask
  openvino: segmentation_tasks.apis.segmentation.OpenVINOSegmentationTask
  nncf: segmentation_tasks.apis.segmentation.OTESegmentationNNCFTask

# Capabilities.
capabilities:
  - compute_representations

# Hyperparameters.
hyper_parameters:
  base_path: ../../../segmentation_tasks/apis/segmentation/configuration.yaml
  parameter_overrides:
    learning_parameters:
      batch_size:
        default_value: 8
        auto_hpo_state: POSSIBLE
      learning_rate:
        default_value: 0.001
        auto_hpo_state: POSSIBLE
      learning_rate_fixed_iters:
        default_value: 0
      learning_rate_warmup_iters:
        default_value: 80
      num_iters:
        default_value: 180
    pot_parameters:
      preset:
        default_value: Mixed
      stat_subset_size:
        default_value: 500
    nncf_optimization:
      enable_quantization:
        default_value: true
      enable_pruning:
        default_value: false
      pruning_supported:
        default_value: false
      maximal_accuracy_degradation:
        default_value: 1.0

# Training resources.
max_nodes: 1
training_targets:
  - GPU
  - CPU

# Stats.
gigaflops: 3.45
size: 4.5
