# Basic Information for Config
framework: mmpretrain
task: Classification
train_type: Incremental

# Model Configuration
model:
  type: SAMImageClassifier
  backbone:
    pretrained: true
    type: OTXEfficientNet
    version: b0
  head:
    in_channels: -1
    loss:
      loss_weight: 1.0
      type: CrossEntropyLoss
    num_classes: 1000
    topk: !!python/tuple
      - 1
      - 5
    type: CustomLinearClsHead
  neck:
    type: GlobalAveragePooling
  pretrained: null

# Data Configuration
data_preprocessor:
  mean:
    - 123.675
    - 116.28
    - 103.53
  std:
    - 58.395
    - 57.12
    - 57.375
  to_rgb: true

train_dataloader:
  batch_size: 32
  num_workers: 2
  dataset:
    type: OTXClsDataset
    pipeline:
      - scale: 224
        type: Resize
      - direction: horizontal
        prob: 0.5
        type: RandomFlip
      - config_str: augmix-m5-w3-d1
        type: AugMixAugment
      - angle: !!python/tuple
          - -10
          - 10
        p: 0.35
        type: RandomRotate
      - type: PackInputs

val_dataloader:
  batch_size: 32
  num_workers: 2
  dataset:
    type: OTXClsDataset
    pipeline:
      - scale: 224
        type: Resize
      - type: PackInputs
    test_mode: true

test_dataloader:
  batch_size: 32
  num_workers: 2
  dataset:
    type: OTXClsDataset
    pipeline:
      - scale: 224
        type: Resize
      - type: PackInputs
    test_mode: true

# Hooks
default_hooks:
  logger:
    type: LoggerHook
    interval: 100
  timer:
    type: IterTimerHook
  param_scheduler:
    type: CosineAnnealingLR
  checkpoint:
    interval: 1
    max_keep_ckpts: 1
    save_best: auto
    type: CheckpointHook
  visualization:
    type: VisualizationHook
    enable: false

# Visualizer
visualizer:
  type: UniversalVisualizer
  vis_backends:
    - type: LocalVisBackend
    - type: TensorboardVisBackend
env_cfg:
  cudnn_benchmark: true
  dist_cfg:
    backend: nccl
    linear_scale_lr: true
deterministic: false

# Evaluation
val_evaluator:
  - type: Accuracy
    topk: !!python/tuple
      - 1
      - 5
test_evaluator:
  - type: Accuracy
    topk: !!python/tuple
      - 1
      - 5

# Optimizer
optim_wrapper:
  type: AmpOptimWrapper # Automatic-Mixed Precision
  dtype: float16 # FP16
  loss_scale: 512.0
  optimizer:
    type: SGD
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0005
