# Description.
model_template_id: Custom_Image_Classification_EfficinetNet-B0
name: EfficientNet-B0
task_type: CLASSIFICATION
task_family: VISION
instantiation: "CLASS"
summary: Class-Incremental Image Classification for EfficientNet-B0
application: ~

# Algo backend.
framework: OTEClassification v1.2.3

# Task implementations.
entrypoints:
  base: mpa_tasks.apis.classification.ClassificationTrainTask
  openvino: torchreid_tasks.openvino_task.OpenVINOClassificationTask
  nncf: mpa_tasks.apis.classification.ClassificationNNCFTask
base_model_path: ../../../../deep-object-reid/configs/ote_custom_classification/efficientnet_b0/template_experimental.yaml

# Capabilities.
capabilities:
  - compute_representations

# Hyperparameters.
hyper_parameters:
  base_path: ../configuration.yaml
  parameter_overrides:
    learning_parameters:
      batch_size:
        default_value: 64
        auto_hpo_state: POSSIBLE
      num_workers:
        default_value: 0
      learning_rate:
        default_value: 0.007
        auto_hpo_state: POSSIBLE
      learning_rate_warmup_iters:
        default_value: 0
      num_iters:
        default_value: 20
    algo_backend:
      train_type:
        default_value: Incremental

# Training resources.
max_nodes: 1
training_targets:
  - GPU
  - CPU

# Stats.
gigaflops: 0.81
size: 4.09
