# Description.
model_template_id: Custom_Image_Classification_MobileNet-V3-small
name: MobileNet-V3-small
task_type: CLASSIFICATION
task_family: VISION
instantiation: "CLASS"
summary: Class-Incremental Image Classification for MobileNet-V3-small
application: ~

# Algo backend.
framework: OTEClassification v1.2.3

# Task implementations.
entrypoints:
  base: otx.algorithms.classification.tasks.ClassificationTrainTask
  openvino: otx.algorithms.classification.tasks.ClassificationOpenVINOTask
  nncf: otx.algorithms.classification.tasks.nncf.ClassificationNNCFTask

# Capabilities.
capabilities:
  - compute_representations

# Hyperparameters.
hyper_parameters:
  base_path: ../configuration.yaml
  parameter_overrides:
    learning_parameters:
      batch_size:
        default_value: 32
        auto_hpo_state: POSSIBLE
      learning_rate:
        default_value: 0.016
        auto_hpo_state: POSSIBLE
      learning_rate_warmup_iters:
        default_value: 100
      num_iters:
        default_value: 20
    algo_backend:
      train_type:
        default_value: Incremental

# Training resources.
max_nodes: 1
training_targets:
  - GPU
  - CPU

# Stats.
gigaflops: 0.12
size: 1.56
