metric: accuracy
search_algorithm: asha
hp_space:
  learning_parameters.learning_rate:
    param_type: qloguniform
    range:
      - 0.0032
      - 0.08
      - 0.0001
  learning_parameters.batch_size:
    param_type: qloguniform
    range:
      - 20
      - 48
      - 2
