lr_finder:
  enable: False
  mode: TPE
  stop_after: False
  num_epochs: 6
  step: 0.001
  smooth_f: 0.01
  epochs_warmup: 1
  path_to_savefig: 'lr_finder.jpg'
  max_lr: 0.03
  min_lr: 0.003
  n_trials: 15

model:
  name: 'efficientnetv2_s_21k'
  type: 'classification'
  pretrained: True
  save_all_chkpts: False
  export_onnx_opset: 11

custom_datasets:
  roots: ['data/CIFAR100/train', 'data/CIFAR100/val']
  types: ['classification_image_folder', 'classification_image_folder']

data:
  root: './'
  height: 224
  width: 224
  norm_mean: [0.5, 0.5, 0.5]
  norm_std: [0.5, 0.5, 0.5]
  save_dir: 'output/efficientv2_s_21k/log'
  workers: 6
  transforms:
    random_flip:
      enable: True
      p: 0.5
    random_rotate:
      enable: True
      p: 0.35
      angle: (-10,10)
    augmix:
      enable: True
      cfg_str: "augmix-m5-w3"
    cutout:
      enable: True
      cutout_factor: 0.35
      p: 0.35

loss:
  name: 'am_softmax'
  softmax:
    compute_s: True

sampler:
  train_sampler: 'RandomSampler'

train:
  optim: 'sam'
  lr: 0.005
  nbd: True
  max_epoch: 200
  weight_decay: 5e-4
  batch_size: 64
  fixbase_epoch: 0
  lr_scheduler: 'warmup'
  warmup: 5
  base_scheduler: 'reduce_on_plateau'
  early_stopping: True
  train_patience: 5
  lr_decay_factor: 200
  deterministic: True
  patience: 5
  gamma: 0.1
  sam:
    rho: 0.05
  ema:
    enable: True
    ema_decay: 0.999
  mix_precision: True

test:
  batch_size: 128
  evaluate: False
  eval_freq: 1
