description: Configuration for an semantic segmentation task
header: Configuration for an semantic segmentation task
id: ""
learning_parameters:
  batch_size:
    affects_outcome_of: TRAINING
    auto_hpo_state: NOT_POSSIBLE
    auto_hpo_value: null
    default_value: 8
    description:
      The number of training samples seen in each iteration of training.
      Increasing this value improves training time and may make the training more
      stable. A larger batch size has higher memory requirements.
    editable: true
    header: Batch size
    max_value: 64
    min_value: 1
    type: INTEGER
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    value: 8
    visible_in_ui: true
    warning:
      Increasing this value may cause the system to use more memory than available,
      potentially causing out of memory errors, please update with caution.
  description: Learning Parameters
  header: Learning Parameters
  learning_rate:
    affects_outcome_of: TRAINING
    auto_hpo_state: NOT_POSSIBLE
    auto_hpo_value: null
    default_value: 0.001
    description:
      Increasing this value will speed up training convergence but might
      make it unstable.
    editable: true
    header: Learning rate
    max_value: 0.1
    min_value: 1.0e-05
    type: FLOAT
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    value: 0.001
    visible_in_ui: true
    warning: null
  learning_rate_fixed_iters:
    affects_outcome_of: TRAINING
    auto_hpo_state: not_possible
    auto_hpo_value: null
    default_value: 100
    description: ""
    editable: true
    header: Number of iterations for fixed learning rate
    max_value: 5000
    min_value: 0
    type: INTEGER
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    value: 100
    visible_in_ui: true
    warning: null
  learning_rate_warmup_iters:
    affects_outcome_of: TRAINING
    auto_hpo_state: not_possible
    auto_hpo_value: null
    default_value: 100
    description: ""
    editable: true
    header: Number of iterations for learning rate warmup
    max_value: 5000
    min_value: 0
    type: INTEGER
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    value: 100
    visible_in_ui: true
    warning: null
  num_checkpoints:
    affects_outcome_of: NONE
    auto_hpo_state: not_possible
    auto_hpo_value: null
    default_value: 5
    description: ""
    editable: true
    header: Number of checkpoints that is done during the single training round
    max_value: 100
    min_value: 1
    type: INTEGER
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    value: 5
    visible_in_ui: true
    warning: null
  num_iters:
    affects_outcome_of: TRAINING
    auto_hpo_state: not_possible
    auto_hpo_value: null
    default_value: 1
    description:
      Increasing this value causes the results to be more robust but training
      time will be longer.
    editable: true
    header: Number of training iterations
    max_value: 100000
    min_value: 1
    type: INTEGER
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    value: 1
    visible_in_ui: true
    warning: null
  num_workers:
    affects_outcome_of: NONE
    auto_hpo_state: not_possible
    auto_hpo_value: null
    default_value: 4
    description:
      Increasing this value might improve training speed however it might
      cause out of memory errors. If the number of workers is set to zero, data loading
      will happen in the main training thread.
    editable: true
    header: Number of cpu threads to use during batch generation
    max_value: 8
    min_value: 0
    type: INTEGER
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    value: 4
    visible_in_ui: true
    warning: null
  type: PARAMETER_GROUP
  visible_in_ui: true
nncf_optimization:
  description: Optimization by NNCF
  enable_pruning:
    affects_outcome_of: TRAINING
    auto_hpo_state: not_possible
    auto_hpo_value: null
    default_value: false
    description: Enable filter pruning algorithm
    editable: true
    header: Enable filter pruning algorithm
    type: BOOLEAN
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    value: false
    visible_in_ui: true
    warning: null
  enable_quantization:
    affects_outcome_of: TRAINING
    auto_hpo_state: not_possible
    auto_hpo_value: null
    default_value: true
    description: Enable quantization algorithm
    editable: true
    header: Enable quantization algorithm
    type: BOOLEAN
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    value: true
    visible_in_ui: true
    warning: null
  header: Optimization by NNCF
  maximal_accuracy_degradation:
    affects_outcome_of: TRAINING
    auto_hpo_state: not_possible
    auto_hpo_value: null
    default_value: 1.0
    description: The maximal allowed accuracy metric drop
    editable: true
    header: Maximum accuracy degradation
    max_value: 100.0
    min_value: 0.0
    type: FLOAT
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    value: 1.0
    visible_in_ui: true
    warning: null
  pruning_supported:
    affects_outcome_of: TRAINING
    auto_hpo_state: not_possible
    auto_hpo_value: null
    default_value: false
    description: Whether filter pruning is supported
    editable: true
    header: Whether filter pruning is supported
    type: BOOLEAN
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    value: false
    visible_in_ui: true
    warning: null
  type: PARAMETER_GROUP
  visible_in_ui: false
postprocessing:
  blur_strength:
    affects_outcome_of: INFERENCE
    auto_hpo_state: not_possible
    auto_hpo_value: null
    default_value: 1
    description:
      With a higher value, the segmentation output will be smoother, but
      less accurate.
    editable: true
    header: Blur strength
    max_value: 25
    min_value: 1
    type: INTEGER
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    value: 1
    visible_in_ui: true
    warning: null
  class_name:
    affects_outcome_of: NONE
    auto_hpo_state: not_possible
    auto_hpo_value: null
    default_value: blur_segmentation
    description: Model classes with defined pre- and postprocessing
    editable: false
    enum_name: Models
    header: Model class for inference
    options:
      BlurSegmentation: blur_segmentation
      Segmentation: segmentation
    type: SELECTABLE
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    value: blur_segmentation
    visible_in_ui: true
    warning: null
  description: Postprocessing
  header: Postprocessing
  soft_threshold:
    affects_outcome_of: INFERENCE
    auto_hpo_state: not_possible
    auto_hpo_value: null
    default_value: 0.5
    description:
      The threshold to apply to the probability output of the model, for
      each pixel. A higher value means a stricter segmentation prediction.
    editable: true
    header: Soft threshold
    max_value: 1.0
    min_value: 0.0
    type: FLOAT
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    value: 0.5
    visible_in_ui: true
    warning: null
  type: PARAMETER_GROUP
  visible_in_ui: true
pot_parameters:
  description: POT Parameters
  header: POT Parameters
  preset:
    affects_outcome_of: NONE
    auto_hpo_state: not_possible
    auto_hpo_value: null
    default_value: Performance
    description: Quantization preset that defines quantization scheme
    editable: false
    enum_name: POTQuantizationPreset
    header: Preset
    options:
      MIXED: Mixed
      PERFORMANCE: Performance
    type: SELECTABLE
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    value: Performance
    visible_in_ui: false
    warning: null
  stat_subset_size:
    affects_outcome_of: NONE
    auto_hpo_state: not_possible
    auto_hpo_value: null
    default_value: 300
    description: Number of data samples used for post-training optimization
    editable: true
    header: Number of data samples
    max_value: 9223372036854775807
    min_value: 1
    type: INTEGER
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    value: 300
    visible_in_ui: true
    warning: null
  type: PARAMETER_GROUP
  visible_in_ui: false
type: CONFIGURABLE_PARAMETERS
visible_in_ui: true
