model:
  name: 'fpn_osnet_x1_0'
  pretrained: True
  feature_dim: 512
  fpn:
    enable: True
    dim: 128
    process: 'concatenation'

data:
  type: 'image'
  sources: ['msmt17']
  targets: ['market1501']
  height: 256
  width: 128
  combineall: True
  transforms:
    random_flip:
      enable: True
      p: 0.5
    random_erase:
      enable: True
      p: 0.5
    random_figures:
      enable: False
      p: 0.33
    random_padding:
      enable: True
      p: 0.25
    color_jitter:
      enable: True
      p: 0.8
      saturation: 0.1
      hue: 0.1
      brightness: 0.15
      contrast: 0.15
    random_rotate:
      enable: True
      p: 0.33
    random_gray_scale:
      enable: True
      p: 0.1
    random_grid:
      enable: False
      p: 0.15
  save_dir: 'outputs/reid-0300'

sampler:
  train_sampler: 'RandomIdentitySamplerV2'

loss:
  name: 'am_softmax'
  softmax:
    label_smooth: True
    conf_pen: 0.3
    m: 0.35
    s: 30

train:
  optim: 'amsgrad'
  lr: 0.0015
  max_epoch: 64
  batch_size: 64
  fixbase_epoch: 5
  open_layers: ['classifier', 'fc']
  lr_scheduler: 'multi_step_warmup'
  stepsize: [40, 50]
  warmup: 4
  warmup_factor_base: 0.01

test:
  batch_size: 300
  dist_metric: 'cosine'
  normalize_feature: False
  evaluate: False
  eval_freq: 2
  rerank: False
  visactmap: False
  visrank: False
  apply_masks: False
