lr_finder:
  enable: False
  mode: TPE
  stop_after: False
  num_epochs: 6
  step: 0.001
  epochs_warmup: 1
  path_to_savefig: 'lr_finder.jpg'
  max_lr: 0.029
  min_lr: 0.005
  n_trials: 15

model:
  name: 'mobilenetv3_large_075'
  type: 'classification'
  pretrained: True
  save_all_chkpts: False
  feature_dim: 1280

mutual_learning:
  aux_configs: ['aux_model.yaml']

custom_datasets:
  roots: ['data/CIFAR100/train', 'data/CIFAR100/val']
  types: ['classification_image_folder', 'classification_image_folder']

data:
  root: './'
  height: 224
  width: 224
  norm_mean: [0.485, 0.456, 0.406]
  norm_std: [0.229, 0.224, 0.225]
  save_dir: 'output/mobilenetv3_large_075/log'
  workers: 6
  transforms:
    random_flip:
      enable: True
      p: 0.5
    random_rotate:
      enable: True
      p: 0.35
      angle: (-10,10)
    cutout:
      enable: True
      cutout_factor: 0.35
      p: 0.35
    augmix:
      enable: True
      cfg_str: "augmix-m4-w2"

loss:
  name: 'softmax'
  softmax:
    s: 1.0
    compute_s: False

sampler:
  train_sampler: 'RandomSampler'

train:
  optim: 'sam'
  lr: 0.013
  nbd: True
  max_epoch: 200
  weight_decay: 5e-4
  batch_size: 100
  lr_scheduler: 'warmup'
  warmup: 15
  base_scheduler: 'reduce_on_plateau'
  early_stopping: True
  train_patience: 5
  lr_decay_factor: 200
  deterministic: True
  patience: 5
  gamma: 0.1
  sam:
    rho: 0.15
  ema:
    enable: True
    ema_decay: 0.999
  mix_precision: True

test:
  batch_size: 128
  evaluate: False
  eval_freq: 1
