metric: mDice
search_algorithm: smbo
early_stop: None
max_iterations: 30
hp_space:
  learning_parameters.learning_rate:
    param_type: quniform
    range:
      - 0.001
      - 0.1
      - 0.001
  learning_parameters.batch_size:
    param_type: qloguniform
    range:
      - 4
      - 8
      - 2
