# Description.
model_template_id: ote_anomaly_classification_stfpm
name: STFPM
task_type: ANOMALY_CLASSIFICATION
task_family: VISION
instantiation: "CLASS"
summary: STFPM with ResNet-18 backbone
application: ~

# Algo backend.
framework: OTEAnomalyClassification v0.1.0

# Task implementations.
entrypoints:
  base: anomaly_classification.AnomalyClassificationTask
  openvino: anomaly_classification.OpenVINOAnomalyClassificationTask

# Hyper Parameters
hyper_parameters:
  base_path: ./configuration.yaml
  parameter_overrides:
    pot_parameters:
      preset:
        default_value: Performance
      stat_subset_size:
        default_value: 300

# Training resources.
max_nodes: 1
training_targets:
  - GPU
  - CPU

# Computational Complexity
gigaflops: 5.6
size: 21.1
