class_path: otx.core.model.entity.detection.MMDetCompatibleModel
init_args:
  config:
    load_from: https://storage.openvinotoolkit.org/repositories/openvino_training_extensions/models/object_detection/v2/yolox_tiny_8x8.pth
    train_cfg:
      assigner:
        type: SimOTAAssigner
        center_radius: 2.5
    test_cfg:
      score_thr: 0.01
      nms:
        type: nms
        iou_threshold: 0.65
      max_per_img: 100
    type: YOLOX
    data_preprocessor:
      type: DetDataPreprocessor
      mean:
        - 123.675
        - 116.28
        - 103.53
      std:
        - 58.395
        - 57.12
        - 57.375
      bgr_to_rgb: true
      pad_size_divisor: 32
    backbone:
      type: CSPDarknet
      deepen_factor: 0.33
      widen_factor: 0.375
      out_indices:
        - 2
        - 3
        - 4
    neck:
      type: YOLOXPAFPN
      in_channels:
        - 96
        - 192
        - 384
      out_channels: 96
      num_csp_blocks: 1
    bbox_head:
      type: YOLOXHead
      num_classes: 80
      in_channels: 96
      feat_channels: 96
# data: detection_yolox_tiny
# optimizer: torch.optim.SGD: lr=0.0005, momentum=0.9, weight_decay=0.001
# scheduler: lightning.pytorch.cli.ReduceLROnPlateau: factor=0.5, patience=1, monitor=train/loss
