_target_: otx.core.model.module.segmentation.OTXSegmentationLitModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.00006
  betas: [0.9, 0.999]
  weight_decay: 0.01

scheduler:
  _target_: torch.optim.lr_scheduler.PolynomialLR
  _partial_: true

otx_model:
  _target_: otx.core.model.entity.segmentation.MMSegCompatibleModel
  config: ???
  num_classes: ???

# compile model for faster training with pytorch 2.0
torch_compile: false

export_config:
  export_format: OPENVINO
  precision: FP32
