metric: mAP
search_algorithm: smbo
early_stop: median_stop
hp_space:
  learning_parameters.learning_rate:
    param_type: quniform
    range:
      - 0.005
      - 0.029
      - 0.001
  learning_parameters.batch_size:
    param_type: qloguniform
    range:
      - 8
      - 64
      - 2
