dataset:
  description: Dataset Parameters
  header: Dataset Parameters
  num_workers:
    affects_outcome_of: NONE
    auto_hpo_state: not_possible
    auto_hpo_value: null
    default_value: 8
    description:
      Increasing this value might improve training speed however it might
      cause out of memory errors. If the number of workers is set to zero, data loading
      will happen in the main training thread.
    editable: true
    header: Number of workers
    max_value: 36
    min_value: 0
    type: INTEGER
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    visible_in_ui: true
    warning: null
  type: PARAMETER_GROUP
  visible_in_ui: true
description: Configuration for Draem
header: Configuration for Draem
learning_parameters:
  description: Learning Parameters
  early_stopping:
    description: Early Stopping Parameters
    header: Early Stopping Parameters
    metric:
      affects_outcome_of: NONE
      auto_hpo_state: not_possible
      auto_hpo_value: null
      default_value: image_AUROC
      description: The metric used to determine if the model should stop training
      editable: true
      enum_name: EarlyStoppingMetrics
      header: Early Stopping Metric
      options:
        IMAGE_F1: image_F1Score
        IMAGE_ROC_AUC: image_AUROC
      type: SELECTABLE
      ui_rules:
        action: DISABLE_EDITING
        operator: AND
        rules: []
        type: UI_RULES
      visible_in_ui: true
      warning: null
    patience:
      affects_outcome_of: TRAINING
      auto_hpo_state: not_possible
      auto_hpo_value: null
      default_value: 20
      description:
        Number of epochs to wait for an improvement in the monitored metric.
        If the metric has not improved for this many epochs, the training will stop
        and the best model will be returned.
      editable: true
      header: Early Stopping Patience
      max_value: 100
      min_value: 1
      type: INTEGER
      ui_rules:
        action: DISABLE_EDITING
        operator: AND
        rules: []
        type: UI_RULES
      visible_in_ui: true
      warning:
        Setting this value too low might lead to underfitting. Setting the
        value too high will increase the training time and might lead to overfitting.
    type: PARAMETER_GROUP
    visible_in_ui: true
  header: Learning Parameters
  lr:
    affects_outcome_of: NONE
    auto_hpo_state: not_possible
    auto_hpo_value: null
    default_value: 0.0001
    description: Learning rate used for optimizing the network.
    editable: true
    header: Learning Rate
    max_value: 1
    min_value: 0.0001
    type: FLOAT
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    visible_in_ui: true
    warning: null
  max_epochs:
    affects_outcome_of: TRAINING
    auto_hpo_state: not_possible
    auto_hpo_value: null
    default_value: 700
    description: Maximum number of epochs to train the model for.
    editable: true
    header: Max Epochs
    max_value: 700
    min_value: 1
    type: INTEGER
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    visible_in_ui: true
    warning:
      Training for very few epochs might lead to poor performance. If Early
      Stopping is enabled then increasing the value of max epochs might not lead to
      desired result.
  train_batch_size:
    affects_outcome_of: TRAINING
    auto_hpo_state: not_possible
    auto_hpo_value: null
    default_value: 8
    description:
      The number of training samples seen in each iteration of training.
      Increasing this value improves training time and may make the training more
      stable. A larger batch size has higher memory requirements.
    editable: true
    header: Batch size
    max_value: 512
    min_value: 1
    type: INTEGER
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    visible_in_ui: true
    warning:
      Increasing this value may cause the system to use more memory than available,
      potentially causing out of memory errors, please update with caution.
  type: PARAMETER_GROUP
  visible_in_ui: true
nncf_optimization:
  description: Optimization by NNCF
  enable_pruning:
    affects_outcome_of: NONE
    auto_hpo_state: not_possible
    auto_hpo_value: null
    default_value: false
    description: Enable filter pruning algorithm
    editable: true
    header: Enable filter pruning algorithm
    type: BOOLEAN
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    visible_in_ui: true
    warning: null
  enable_quantization:
    affects_outcome_of: NONE
    auto_hpo_state: not_possible
    auto_hpo_value: null
    default_value: true
    description: Enable quantization algorithm
    editable: true
    header: Enable quantization algorithm
    type: BOOLEAN
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    visible_in_ui: true
    warning: null
  header: Optimization by NNCF
  pruning_supported:
    affects_outcome_of: TRAINING
    auto_hpo_state: not_possible
    auto_hpo_value: null
    default_value: false
    description: Whether filter pruning is supported
    editable: false
    header: Whether filter pruning is supported
    type: BOOLEAN
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    value: false
    visible_in_ui: false
    warning: null
  type: PARAMETER_GROUP
  visible_in_ui: true
pot_parameters:
  description: POT Parameters
  header: POT Parameters
  preset:
    affects_outcome_of: NONE
    auto_hpo_state: not_possible
    auto_hpo_value: null
    default_value: Performance
    description: Quantization preset that defines quantization scheme
    editable: true
    enum_name: POTQuantizationPreset
    header: Preset
    options:
      MIXED: Mixed
      PERFORMANCE: Performance
    type: SELECTABLE
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    visible_in_ui: true
    warning: null
  stat_subset_size:
    affects_outcome_of: NONE
    auto_hpo_state: not_possible
    auto_hpo_value: null
    default_value: 300
    description: Number of data samples used for post-training optimization
    editable: true
    header: Number of data samples
    max_value: 1000
    min_value: 1
    type: INTEGER
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    visible_in_ui: true
    warning: null
  type: PARAMETER_GROUP
  visible_in_ui: false
type: CONFIGURABLE_PARAMETERS
visible_in_ui: true
