# Description.
model_template_id: Custom_Counting_Instance_Segmentation_MaskRCNN_EfficientNetB2B
name: MaskRCNN-EfficientNetB2B
task_type: INSTANCE_SEGMENTATION
task_family: VISION
instantiation: "CLASS"
summary: Counting algorithm provides counting of objects and object instance masks. This model is based on MaskRCNN-EfficientNetB2B which is faster in training and inference but less accurate.
application: ~

# Algo backend.
framework: OTEDetection v2.9.1

# Task implementations.
entrypoints:
  base: detection_tasks.apis.detection.OTEDetectionTrainingTask
  openvino: detection_tasks.apis.detection.OpenVINODetectionTask
  nncf: detection_tasks.apis.detection.OTEDetectionNNCFTask

# Capabilities.
capabilities:
  - compute_representations

# Hyperparameters.
hyper_parameters:
  base_path: ../../../../mmdetection/detection_tasks/apis/detection/configuration.yaml
  parameter_overrides:
    learning_parameters:
      batch_size:
        default_value: 4
      learning_rate:
        default_value: 0.015
      learning_rate_warmup_iters:
        default_value: 200
      num_iters:
        default_value: 300
    nncf_optimization:
      enable_quantization:
        default_value: true
      enable_pruning:
        default_value: false
      pruning_supported:
        default_value: false
      maximal_accuracy_degradation:
        default_value: 1.0

# Training resources.
max_nodes: 1
training_targets:
  - GPU
  - CPU

# Stats.
gigaflops: 68.48
size: 13.27
