# Description.
model_template_id: Custom_Image_Classification_EfficientNet-V2-S
name: EfficientNet-V2-S
task_type: CLASSIFICATION
task_family: VISION
instantiation: "CLASS"
summary: This model is quite slow, but provides superior single and multi label classification performance.
application:
  ~

# Algo backend.
framework: OTEClassification v1.2.3

# Task implementations.
entrypoints:
  base: torchreid.integration.sc.train_task.OTEClassificationTrainingTask
  openvino: torchreid.integration.sc.openvino_task.OpenVINOClassificationTask
  nncf: torchreid.integration.sc.nncf_task.OTEClassificationNNCFTask

# Capabilities.
capabilities:
  - compute_representations
  - compute_uncertainty_score

# Hyperparameters.
hyper_parameters:
  base_path: "../../../torchreid/integration/sc/configuration.yaml"
  parameter_overrides:
    learning_parameters:
      batch_size:
        default_value: 32
      max_num_epochs:
        default_value: 200
      learning_rate:
        default_value: 0.007
      enable_early_stopping:
        default_value: true
    nncf_optimization:
      enable_quantization:
        default_value: true
      enable_pruning:
        default_value: false
      maximal_accuracy_degradation:
        default_value: 1.0

# Training resources.
max_nodes: 1
training_targets:
  - GPU
  - CPU

# Stats.
gigaflops: 5.76
size: 20.23
