# Description.
model_template_id: Custom_Image_Classification_MobileNet-V3-large-1x
name: MobileNet-V3-large-1x
task_type: CLASSIFICATION
task_family: VISION
instantiation: "CLASS"
summary: Class-Incremental Image Classification for MobileNet-V3-large-1x
application: ~

# Algo backend.
framework: OTEClassification v1.2.3

# Task implementations.
entrypoints:
  base: otx.algorithms.classification.tasks.ClassificationTrainTask
  openvino: otx.algorithms.classification.tasks.ClassificationOpenVINOTask
  nncf: otx.algorithms.classification.tasks.nncf.ClassificationNNCFTask

# Capabilities.
capabilities:
  - compute_representations

# Hyperparameters.
hyper_parameters:
  base_path: ../configuration.yaml
  parameter_overrides:
    learning_parameters:
      batch_size:
        default_value: 64
        auto_hpo_state: POSSIBLE
      learning_rate:
        default_value: 0.0058
        auto_hpo_state: POSSIBLE
      learning_rate_warmup_iters:
        default_value: 10
      num_iters:
        default_value: 90
    nncf_optimization:
      enable_quantization:
        default_value: true
      enable_pruning:
        default_value: false
      pruning_supported:
        default_value: true
      maximal_accuracy_degradation:
        default_value: 1.0
    algo_backend:
      train_type:
        default_value: Incremental

# Training resources.
max_nodes: 1
training_targets:
  - GPU
  - CPU

# Stats.
gigaflops: 0.44
size: 4.29
