# Description.
model_template_id: ClassIncremental_Instance_Segmentation_MaskRCNN_ResNet50
name: MaskRCNN-ResNet50-ClsIncr
task_type: INSTANCE_SEGMENTATION
task_family: VISION
instantiation: "CLASS"
summary: Class-Incremental Instance Segmentation for MaskRCNN-ResNet50
application: ~

# Algo backend.
framework: OTEDetection v2.9.1

# Task implementations.
entrypoints:
  base: mpa_tasks.apis.detection.DetectionTrainTask
  openvino: detection_tasks.apis.detection.OpenVINODetectionTask

# Capabilities.
capabilities: []

# Hyperparameters.
hyper_parameters:
  base_path: ../configuration.yaml
  parameter_overrides:
    learning_parameters:
      batch_size:
        default_value: 8
      learning_rate:
        default_value: 0.001
      learning_rate_warmup_iters:
        default_value: 100
      num_iters:
        default_value: 300
    algo_backend:
      train_type:
        default_value: Incremental

# Training resources.
max_nodes: 1
training_targets:
  - GPU
  - CPU

# TODO
# Stats.
gigaflops: 533.8
size: 177.9
