description: Configuration for SAM
header: Configuration for SAM
id: ""
learning_parameters:
  description: Learning Parameters
  header: Learning Parameters
  type: PARAMETER_GROUP
  visible_in_ui: true
  trainer:
    description: Trainer Parameters
    header: Trainer Parameters
    type: PARAMETER_GROUP
    visible_in_ui: true
    max_epochs:
      affects_outcome_of: TRAINING
      default_value: 1
      description:
        Maximum number of epochs to train for. If not specified, the training will
        run until the early stopping criteria is met.
      editable: true
      header: Maximum number of epochs
      max_value: 1
      min_value: 1
      type: INTEGER
      value: 1
  dataset:
    description: Dataset Parameters
    header: Dataset Parameters
    type: PARAMETER_GROUP
    visible_in_ui: true
    use_mask:
      header: Flag about using mask as label
      affects_outcome_of: TRAINING
      default_value: false
      description: If using mask as-is (true) or converting it to polygon (false)
      editable: true
      value: false
      type: BOOLEAN
    train_batch_size:
      affects_outcome_of: TRAINING
      auto_hpo_state: not_possible
      auto_hpo_value: null
      default_value: 1
      description:
        The number of training samples seen in each iteration of training.
        Increasing this value improves training time and may make the training more
        stable. A larger batch size has higher memory requirements.
      editable: true
      header: Batch size
      max_value: 512
      min_value: 1
      type: INTEGER
      ui_rules:
        action: DISABLE_EDITING
        operator: AND
        rules: []
        type: UI_RULES
      value: 32
      visible_in_ui: true
      warning:
        Increasing this value may cause the system to use more memory than available,
        potentially causing out of memory errors, please update with caution.
pot_parameters:
  description: POT Parameters
  header: POT Parameters
  preset:
    affects_outcome_of: NONE
    auto_hpo_state: not_possible
    auto_hpo_value: null
    default_value: Mixed
    description: Quantization preset that defines quantization scheme
    editable: true
    enum_name: POTQuantizationPreset
    header: Preset
    options:
      MIXED: Mixed
      PERFORMANCE: Performance
    type: SELECTABLE
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    value: Mixed
    visible_in_ui: true
    warning: null
  stat_subset_size:
    affects_outcome_of: NONE
    auto_hpo_state: not_possible
    auto_hpo_value: null
    default_value: 300
    description: Number of data samples used for post-training optimization
    editable: true
    header: Number of data samples
    max_value: 1000
    min_value: 1
    type: INTEGER
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    value: 300
    visible_in_ui: true
    warning: null
  type: PARAMETER_GROUP
  visible_in_ui: false
postprocessing:
  confidence_threshold:
    affects_outcome_of: INFERENCE
    default_value: 0.5
    description:
      This threshold only takes effect if the threshold is not set based
      on the result.
    editable: true
    header: Confidence threshold
    max_value: 1
    min_value: 0
    type: FLOAT
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    value: 0.5
    visible_in_ui: true
    warning: null
  description: Postprocessing
  header: Postprocessing
  result_based_confidence_threshold:
    affects_outcome_of: INFERENCE
    default_value: false
    description: Confidence threshold is derived from the results
    editable: true
    header: Result based confidence threshold
    type: BOOLEAN
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    value: false
    visible_in_ui: true
    warning: null
  type: PARAMETER_GROUP
  visible_in_ui: true
algo_backend:
  description: parameters for algo backend
  header: Algo backend parameters
  train_type:
    affects_outcome_of: TRAINING
    default_value: Incremental
    description: Training scheme option that determines how to train the model
    editable: True
    enum_name: TrainType
    header: Train type
    options:
      Incremental: "Incremental"
      Zeroshot: "Zeroshot"
    type: SELECTABLE
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    value: Incremental
    visible_in_ui: false
    warning: null
  mem_cache_size:
    affects_outcome_of: TRAINING
    default_value: 1000000000
    description: Size of memory pool for caching decoded data to load data faster (bytes).
    editable: true
    header: Size of memory pool
    max_value: 9223372036854775807
    min_value: 0
    type: INTEGER
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    visible_in_ui: false
    warning: null
  storage_cache_scheme:
    affects_outcome_of: TRAINING
    default_value: NONE
    description: Scheme for storage cache
    editable: true
    enum_name: StorageCacheScheme
    header: Scheme for storage cache
    options:
      NONE: "NONE"
      AS_IS: "AS-IS"
      JPEG_75: "JPEG/75"
      JPEG_95: "JPEG/95"
      PNG: "PNG"
      TIFF: "TIFF"
    type: SELECTABLE
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    visible_in_ui: false
    warning: null
  type: PARAMETER_GROUP
  visible_in_ui: false
type: CONFIGURABLE_PARAMETERS
visible_in_ui: true
