# Description.
model_template_id: Custom_Semantic_Segmentation_SegNext_t
name: SegNext-t
task_type: SEGMENTATION
task_family: VISION
instantiation: "CLASS"
summary: Class-Incremental Semantic Segmentation with small-sized architecture which based on the MSCAN backbone for faster inference while preserving competetive accuracy.
application: ~

# Algo backend.
framework: OTXSegmentation v0.14.0

# Task implementations.
entrypoints:
  base: otx.algorithms.segmentation.adapters.mmseg.task.MMSegmentationTask
  openvino: otx.algorithms.segmentation.adapters.openvino.task.OpenVINOSegmentationTask
  nncf: otx.algorithms.segmentation.adapters.mmseg.nncf.task.SegmentationNNCFTask

# Capabilities.
capabilities:
  - compute_representations

# Hyperparameters.
hyper_parameters:
  base_path: ../configuration.yaml
  parameter_overrides:
    learning_parameters:
      batch_size:
        default_value: 8
        auto_hpo_state: POSSIBLE
      learning_rate:
        default_value: 0.00008
        auto_hpo_state: POSSIBLE
      learning_rate_fixed_iters:
        default_value: 0
      learning_rate_warmup_iters:
        default_value: 20
      num_iters:
        default_value: 170
    nncf_optimization:
      enable_quantization:
        default_value: true
      enable_pruning:
        default_value: false
      pruning_supported:
        default_value: false
      maximal_accuracy_degradation:
        default_value: 1.0
    algo_backend:
      train_type:
        default_value: Incremental

# Training resources.
max_nodes: 1
training_targets:
  - GPU
  - CPU

# Stats.
gigaflops: 6.07
size: 4.23
