# Description.
model_template_id: Custom_Object_Detection_YOLOX
name: YOLOX
task_type: DETECTION
task_family: VISION
instantiation: "CLASS"
summary:
  Model with fastest inference speed, more than 2x compared to SSD, and comparable, slightly slower, training time.
  Works best on datasets with large objects, can struggle with small objects.

application: ~

# Algo backend.
framework: OTEDetection v2.9.1

# Task implementations.
entrypoints:
  base: detection_tasks.apis.detection.OTEDetectionTrainingTask
  openvino: detection_tasks.apis.detection.OpenVINODetectionTask
  nncf: detection_tasks.apis.detection.OTEDetectionNNCFTask

# Capabilities.
capabilities:
  - compute_representations

# Hyperparameters.
hyper_parameters:
  base_path: ../../../../mmdetection/detection_tasks/apis/detection/configuration.yaml
  parameter_overrides:
    learning_parameters:
      batch_size:
        default_value: 16
      learning_rate:
        default_value: 0.0025
      learning_rate_warmup_iters:
        default_value: 500
      num_iters:
        default_value: 300
    nncf_optimization:
      enable_quantization:
        default_value: true
      enable_pruning:
        default_value: false
      maximal_accuracy_degradation:
        default_value: 1.0

# Training resources.
max_nodes: 1
training_targets:
  - GPU
  - CPU

# Stats.
gigaflops: 6.5
size: 20.4
