lr_finder:
  enable: False
  mode: TPE
  stop_after: False
  num_epochs: 7
  step: 0.001
  epochs_warmup: 1
  path_to_savefig: 'lr_finder.jpg'
  max_lr: 1e-3
  min_lr: 1e-5
  n_trials: 15

model:
  name: 'mobilenetv3_small'
  type: 'multihead'
  pretrained: True
  save_all_chkpts: False
  dropout_cls:
    p: 0.1

custom_datasets:
  roots: ['mlc_voc_2007/train_mh_full.json', 'mlc_voc_2007/val_mh_full.json']
  types: ['multihead_classification', 'multihead_classification']

data:
  root: './'
  height: 224
  width: 224
  norm_mean: [0.485, 0.456, 0.406]
  norm_std: [0.229, 0.224, 0.225]
  save_dir: 'output/mulitihead/mobilenetv3_small'
  workers: 6
  transforms:
    random_flip:
      enable: True
      p: 0.5
    randaugment:
      enable: True
    cutout:
      enable: True
      cutout_factor: 0.35
      p: 0.35

loss:
  name: 'softmax,asl'
  softmax:
    s: 1.0
    compute_s: False
  asl:
    gamma_pos: 0.
    gamma_neg: 4.

sampler:
  train_sampler: 'RandomSampler'


train:
  optim: 'sam'
  lr: 0.016
  nbd: True
  max_epoch: 80
  weight_decay: 5e-4
  batch_size: 64
  lr_scheduler: 'onecycle'
  early_stopping: True
  pct_start: 0.2
  train_patience: 5
  lr_decay_factor: 1000
  deterministic: True
  target_metric: test_acc
  gamma: 0.1
  sam:
    rho: 0.05
  ema:
    enable: True
    ema_decay: 0.9995
  mix_precision: True

test:
  batch_size: 128
  evaluate: False
  eval_freq: 1
