# Description.
model_template_id: Custom_Semantic_Segmentation_Lite-HRNet-s-mod2_OCR
name: Lite-HRNet-s-mod2
task_type: SEGMENTATION
task_family: VISION
instantiation: "CLASS"
summary: Class-Incremental Semantic Segmentation with lightweight architecture which based on the Lite-HRNet backbone for the fast inference and training on the limited amount of data.
application: ~

# Algo backend.
framework: OTESegmentation v0.14.0

# Task implementations.
entrypoints:
  base: mpa_tasks.apis.segmentation.SegmentationTrainTask
  openvino: segmentation_tasks.apis.segmentation.OpenVINOSegmentationTask
  nncf: mpa_tasks.apis.segmentation.SegmentationNNCFTask
base_model_path: ../../../../mmsegmentation/configs/custom-sematic-segmentation/ocr-lite-hrnet-s-mod2/template_experimental.yaml

# Capabilities.
capabilities:
  - compute_representations

# Hyperparameters.
hyper_parameters:
  base_path: ../configuration.yaml
  parameter_overrides:
    learning_parameters:
      batch_size:
        default_value: 4
      learning_rate:
        default_value: 0.001
      learning_rate_fixed_iters:
        default_value: 0
      learning_rate_warmup_iters:
        default_value: 100
      num_iters:
        default_value: 300
    algo_backend:
      train_type:
        default_value: Incremental

# Training resources.
max_nodes: 1
training_targets:
  - GPU
  - CPU

# Stats.
gigaflops: 1.82
size: 3.5
