metric: accuracy
search_algorithm: asha
hp_space:
  learning_parameters.learning_rate:
    param_type: qloguniform
    range:
      - 0.00001
      - 0.001
      - 0.00001
  learning_parameters.batch_size:
    param_type: qloguniform
    range:
      - 42
      - 96
      - 2
