name: Daily Test

on:
  workflow_dispatch: # run on request (no need for PR)
  schedule:
    # every UTC 7PM from Mon to Fri
    - cron: "0 19 * * 1-5"

# Declare default permissions as read only.
permissions: read-all

jobs:
  Daily-e2e-tests:
    runs-on: [otx-gpu-a10g-1]
    container:
      image: 219678651685.dkr.ecr.eu-west-1.amazonaws.com/ote-ci:11.7.1.2-devel-ubuntu20.04
      options: "--runtime=nvidia --env-file=/home/runner/.nvidia.env --ipc=host"
    strategy:
      fail-fast: false
      matrix:
        include:
          - task: "action"
          - task: "classification"
          - task: "detection"
          - task: "rotated_detection"
          - task: "keypoint_detection"
          - task: "instance_segmentation"
          - task: "semantic_segmentation"
          - task: "visual_prompting"
          - task: "anomaly"
    name: E2E-Test-${{ matrix.task }}-py310
    # This is what will cancel the job concurrency
    concurrency:
      group: ${{ github.workflow }}-E2E-${{ github.event.pull_request.number || github.ref }}-${{ matrix.task }}
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Install Python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: "3.10"
      - name: Install tox
        run: |
          python -m pip install --require-hashes --no-deps -r .ci/requirements.txt
          pip-compile --generate-hashes --output-file=/tmp/requirements.txt --extra=ci_tox pyproject.toml
          python -m pip install --require-hashes --no-deps -r /tmp/requirements.txt
          rm /tmp/requirements.txt
      - name: Run E2E Test
        run: tox -vv -e e2e-test-${{ matrix.task }}
      - name: Upload test results
        uses: actions/upload-artifact@84480863f228bb9747b473957fcc9e309aa96097 # v4.4.2
        with:
          name: ${{ matrix.task }}-py310
          path: .tox/e2e-test-${{ matrix.task }}.csv
        if: ${{ always() }}
