# Description.
model_template_id: Custom_Rotated_Detection_via_Rotated_ATSS_OBB_r50
name: Rotated_ATSS_OBB_r50
task_type: ROTATED_DETECTION
task_family: VISION
instantiation: "CLASS"
summary: Class-Incremental Rotated object detection for RotatedATSS-OBB-r50
application: ~

# Algo backend.
framework: OTXDetection v2.9.1

# Task implementations.
entrypoints:
  base: otx.algorithms.detection.adapters.mmrotate.task.MMRotateTask
  openvino: otx.algorithms.detection.adapters.openvino.task.OpenVINODetectionTask
  nncf: otx.algorithms.detection.adapters.mmdet.nncf.task.DetectionNNCFTask

# Capabilities.
capabilities:
  - compute_representations

# Hyperparameters.
hyper_parameters:
  base_path: ../configuration.yaml
  parameter_overrides:
    learning_parameters:
      batch_size:
        default_value: 4
        auto_hpo_state: POSSIBLE
      learning_rate:
        default_value: 0.0025
        auto_hpo_state: POSSIBLE
      learning_rate_warmup_iters:
        default_value: 100
      num_iters:
        default_value: 100
    pot_parameters:
      stat_requests_number:
        default_value: 1
    nncf_optimization:
      enable_quantization:
        default_value: true
      enable_pruning:
        default_value: false
      pruning_supported:
        default_value: false
      maximal_accuracy_degradation:
        default_value: 1.0
    algo_backend:
      train_type:
        default_value: Incremental

# Training resources.
max_nodes: 1
training_targets:
  - GPU
  - CPU

# Stats.
gigaflops: 0.0
size: 0.0
