# Description.
model_template_id: ClassIncremental_Image_Classification_MobileNet-V3-small
name: MobileNet-V3-small-ClsIncr
task_type: CLASSIFICATION
task_family: VISION
instantiation: "CLASS"
summary: Class-Incremental Image Classification for MobileNet-V3-small
application: ~

# Algo backend.
framework: MPA v1.1.0

# Task implementations.
entrypoints:
  base: mpa_tasks.apis.classification.ClassificationTrainTask
  openvino: torchreid_tasks.openvino_task.OpenVINOClassificationTask

# Capabilities.
capabilities: []

# Hyperparameters.
hyper_parameters:
  base_path: ../configuration.yaml
  parameter_overrides:
    learning_parameters:
      batch_size:
        default_value: 32
      num_workers:
        default_value: 4
      learning_rate:
        default_value: 0.016
      learning_rate_warmup_iters:
        default_value: 100
      num_iters:
        default_value: 20
    algo_backend:
      train_type:
        default_value: Incremental

# Training resources.
max_nodes: 1
training_targets:
  - GPU
  - CPU

# Stats.
gigaflops: 0.12
size: 1.56
